export enum ProcessingStatus {
  RECEIVED = "RECEIVED",
  PARSING = "PARSING",
  AWAITING_FIELD_COMPLETION = "AWAITING_FIELD_COMPLETION",
  AWAITING_DUPLICATE_REVIEW = "AWAITING_DUPLICATE_REVIEW",
  POLICY_LOOKUP = "POLICY_LOOKUP",
  COVERAGE_VALIDATION = "COVERAGE_VALIDATION",
  AWAITING_COVERAGE_REVIEW = "AWAITING_COVERAGE_REVIEW",
  SEVERITY_SCORING = "SEVERITY_SCORING",
  AWAITING_SEVERITY_REVIEW = "AWAITING_SEVERITY_REVIEW",
  ROUTING = "ROUTING",
  AWAITING_ROUTING_OVERRIDE = "AWAITING_ROUTING_OVERRIDE",
  ACKNOWLEDGED = "ACKNOWLEDGED",
  COMPLETED = "COMPLETED",
  HALTED = "HALTED",
}

export enum CoverageStatus {
  CONFIRMED = "CONFIRMED",
  EXCLUDED = "EXCLUDED",
  LAPSED = "LAPSED",
  DISPUTED = "DISPUTED",
  DENIED = "DENIED",
}

export enum SlaStatus {
  ON_TRACK = "ON_TRACK",
  AT_RISK = "AT_RISK",
  BREACHED = "BREACHED",
}

export enum DuplicateResolution {
  MERGE = "MERGE",
  DISTINCT = "DISTINCT",
  REPLACE = "REPLACE",
}

export type DuplicateReviewInput = {
  duplicateCandidateId: string;
  resolution: DuplicateResolution;
};
