"""
Credit packet assembler.

APD §4 task 4.9: prepare a complete credit packet for AM/CO confirmation.
APD Hard Constraint: 'Never apply a credit without APPROVER_ID + AUDIT_REF
in the packet'.

Wave 1 path: packet → 4.9E AM email queue for human Aurum UI entry.
Wave 2 path: packet → 4.10 Aurum UI service-account auto-write.

In Wave 1, the packet is generated by BDRA but submitted by a human via
Aurum UI. APPROVER_ID is filled in by the AM/CO on submission, NOT by BDRA.
This is the structural fix for the Sandra-£170 audit gap: BDRA never writes
its own APPROVER_ID; the human signing the packet does.

Build-loop note: This module surfaced spec gaps #9-12 below.
"""
from __future__ import annotations

from dataclasses import dataclass, field, asdict
from datetime import date
from decimal import Decimal
from enum import Enum


# SPEC GAP #9: REASON_CODE taxonomy is incomplete.
#
# Real APEX_CREDITS data shows only 2 codes: FUEL_RECALC, GOODWILL.
# APD task 4.9 references REASON_CODE without enumerating valid values.
# CLAUDE.md decision 6 mentions "Hayes-class FUEL_SURCH_DAMAGE → goodwill
# ≤ 50% of surcharge" — but FUEL_SURCH_DAMAGE is a DISPUTE_TYPE, not a
# REASON_CODE.
#
# Question for Sarah: full REASON_CODE taxonomy? What about:
#   - INV_CORRECTION (calc error, full reversal)
#   - SLA_BREACH (delivery missed window)
#   - DAMAGE_CLAIM (insured damage; different ledger)
#   - RETENTION (account-tier discount, not dispute-driven)
#
# Build-attempt mitigation: enum constrained to observed codes; novel codes
# rejected by validator. Real impl needs full taxonomy from finance.
class ReasonCode(str, Enum):
    FUEL_RECALC = "FUEL_RECALC"
    GOODWILL = "GOODWILL"
    # Add more after Sarah confirms taxonomy.


# SPEC GAP #10: APPLIED_DT semantics.
#
# Real APEX_CREDITS has APPLIED_DT column. But:
#   - Spec doesn't say if this is the date BDRA generated the packet,
#     the date the AM signed, or the date Aurum actually processed.
#   - In Wave 1 the lag could be hours to days (packet → AM email →
#     review → Aurum UI entry).
#   - If APPLIED_DT = packet generation date, it lies about when the
#     credit actually applied (audit risk).
#   - If APPLIED_DT = Aurum processing date, BDRA can't fill this field
#     at packet generation time — it's filled later by Aurum.
#
# Build decision: leave APPLIED_DT empty in the packet; Aurum (via the
# AM's UI submission) fills it. This means agent_emitted credits in
# APEX_CREDITS will have APPLIED_DT populated by Aurum, not by BDRA.
#
# Real impl needs Sarah / Aurum vendor confirmation.


# SPEC GAP #11: cross-stream dispute_id linkage.
#
# APD §4 task 4.4: cross-stream check for active WS1 delivery exception
# touching the same invoice. If hit, escalate to human.
# But: the credit packet itself doesn't carry the WS1 link — only AUDIT_REF
# (which is BDRA-internal) and INVOICE_NO (which is shared but not
# identifier-shared with delivery exception case IDs).
#
# This means: a credit applied today for a dispute that downstream
# generates from a damage exception cannot be traced back to the WS1
# event in the audit trail. BP-X1 chain is invisible at the credit level.
#
# Decision: add an optional dispute_id field that is NOT written to Aurum
# but IS retained in the BDRA-internal CRM record for cross-stream tracing.
# Real impl: confirm with Sarah whether finance wants WS1 linkage in the
# audit field (would require an extension to AUDIT_REF format or a new
# Aurum column — both ask Aurum vendor).


# SPEC GAP #12: amount precision policy.
#
# Aurum data shows credits to 2 decimal places (£88.00, £45.00).
# Spec doesn't address rounding policy when a calculated remedy lands at
# > 2dp (e.g., 33.333% of £100 = £33.33 or £33.34).
# Decision: Decimal type; round half-even; cap at 2dp.


@dataclass(frozen=True)
class CreditPacket:
    """Immutable credit packet ready for AM/CO confirmation.

    APPROVER_ID is intentionally NOT a field of this packet. It is filled
    in by the human signing the packet at submission time. This is the
    structural fix for the Sandra-£170 audit gap: BDRA cannot self-approve.
    """
    invoice_no: str
    customer_id: str
    credit_amt: Decimal
    reason_code: ReasonCode
    audit_ref: str
    # APPLIED_DT not included — see SPEC GAP #10.
    # APPROVER_ID not included — filled by human signing.

    # BDRA-internal context, not written to Aurum CSV:
    processing_id: str = field(metadata={"aurum": False})
    dispute_id: str | None = field(default=None, metadata={"aurum": False})

    def to_aurum_record(self) -> dict[str, str]:
        """Render packet as the row a human (or Wave 2 RPA) would submit
        to Aurum's APEX_CREDITS table.

        Returns dict with Aurum column names. APPROVER_ID and APPLIED_DT
        are present but empty — caller must populate before submission.
        Validator will reject submission attempts with empty APPROVER_ID.
        """
        return {
            "CREDIT_ID": "",  # assigned by Aurum on insert
            "INVOICE_NO": self.invoice_no,
            "CUSTOMER_ID": self.customer_id,
            "CREDIT_AMT": f"{self.credit_amt:.2f}",
            "REASON_CODE": self.reason_code.value,
            "APPROVER_ID": "",  # filled by human signing — HARD CONSTRAINT
            "AUDIT_REF": self.audit_ref,
            "APPLIED_DT": "",  # filled by Aurum on processing
        }


class PacketValidationError(Exception):
    """Raised when a packet fails the Hard Constraint check."""


def validate_for_submission(
    packet: CreditPacket, approver_id: str, applied_dt: date,
) -> dict[str, str]:
    """Final hard-constraint check before submission to Aurum.

    APD Hard Constraint: 'Never apply a credit without APPROVER_ID +
    AUDIT_REF in the packet'.

    This is the system-enforced gate that fixes the Sandra-£170 gap.
    No code path exists in BDRA to bypass this check.
    """
    if not approver_id or not approver_id.strip():
        raise PacketValidationError(
            "APPROVER_ID is required. BDRA cannot self-approve credits — "
            "a named human must sign before submission."
        )
    if not packet.audit_ref:
        raise PacketValidationError(
            "AUDIT_REF is required and must be generated by BDRA before "
            "packet creation."
        )
    if packet.credit_amt <= Decimal("0.00"):
        raise PacketValidationError(
            f"CREDIT_AMT must be positive; got {packet.credit_amt}"
        )

    record = packet.to_aurum_record()
    record["APPROVER_ID"] = approver_id
    record["APPLIED_DT"] = applied_dt.isoformat()
    return record
